name: Build deb with rootless

on:
  push:
    #tags:
    #  - 'v*'

    #branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Theos
        uses: iosrouter/theos-action@main # Randomblock1/theos-action@v1

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: com.shiftcmdk.autoalerts
          path: ${{ github.workspace }}/packages/*.deb
